package eportfoliogenerator;

/**
 * This class provides the types that will be need to be loaded from
 * language-dependent XML files.
 * 
 * @author McKilla Gorilla & _____________
 */
public enum LanguagePropertyType {
    // TITLE FOR WINDOW TITLE BAR
    // TITLE FOR WINDOW TITLE BAR
    TITLE_WINDOW,
    
    // APPLICATION TOOLTIPS FOR BUTTONS
    // FILE TOOLBAR
    TOOLTIP_NEW_PORTFOLIO,
    TOOLTIP_LOAD_PORTFOLIO,
    TOOLTIP_SAVE_PORTFOLIO,
    TOOLTIP_EXPORT_PORTFOLIO,
    TOOLTIP_SAVE_AS_PORTFOLIO,
    TOOLTIP_EXIT,
    
    //SITE EDIT TOOLBAR
    TOOLTIP_ADD_PAGE,
    TOOLTIP_REMOVE_PAGE,
    
    //WORKSPACE MODE TOOLBAR
    TOOLTIP_SELECT_EDITOR_WORKSPACE,
    TOOLTIP_SELECT_VIEWER_WORKSPACE,
    
    
    //PAGE EDITOR WORKSPACE
    TOOLTIP_EDIT_THE_HYPERLINK,
    TOOLTIP_ADD_TEXT_COMPONENT,
    TOOLTIP_REMOVE_COMPONENT,
    TOOLTIP_ADD_IMAGE_COMPONENT,
    TOOLTIP_ADD_VIDEO_COMPONENT,
    TOOLTIP_ADD_TEXT_HYPERLINK,
    TOOLTIP_EDIT_VIDEO_COMPONENT,
    TOOLTIP_EDIT_SLIDE_SHOW_COMPONENT,
    TOOLTIP_SELECT_BANNER_IMAGE,
    TOOLTIP_EDIT_TEXT_COMPONENT,
    TOOLTIP_EDIT_IMAGE_COMPONENT,
    TOOLTIP_ADD_SLIDESHOW_COMPONENT,
    
    // DEFAULT VALUES
    DEFAULT_PAGE_TITLE,
    DEFAULT_STUDENT_NAME,
    
    // UI LABELS
    LABEL_CAPTION,
    LABEL_PAGE_TITLE,
      
    /* THESE ARE FOR LANGUAGE-DEPENDENT ERROR HANDLING,
     LIKE FOR TEXT PUT INTO DIALOG BOXES TO NOTIFY
     THE USER WHEN AN ERROR HAS OCCURED */
    ERROR_DATA_FILE_LOADING,
    ERROR_PROPERTIES_FILE_LOADING,
    ERROR_NO_SLIDESHOW_IMAGES,
    ERROR_UNEXPECTED
}
