package eportfoliogenerator;

/**
 * This class provides the types that will be need to be loaded from
 * language-dependent XML files.
 * 
 * @author McKilla Gorilla & _____________
 */
public enum LanguagePropertyType {
    // TITLE FOR WINDOW TITLE BAR
    // TITLE FOR WINDOW TITLE BAR
    TITLE_WINDOW,
    
    // APPLICATION TOOLTIPS FOR BUTTONS
    TOOLTIP_NEW_PORTFOLIO,
    TOOLTIP_LOAD_PORTFOLIO,
    TOOLTIP_SAVE_PORTFOLIO,
    TOOLTIP_EXPORT_PORTFOLIO,
    TOOLTIP_SAVE_AS_PORTFOLIO,
    TOOLTIP_EXIT,
    TOOLTIP_ADD_PAGE,
    TOOLTIP_REMOVE_PAGE,
    TOOLTIP_EDIT_THE_HYPERLINK,
    
    // DEFAULT VALUES
    DEFAULT_IMAGE_CAPTION,
    DEFAULT_SLIDE_SHOW_TITLE,
    
    // UI LABELS
    LABEL_CAPTION,
    LABEL_PAGE_TITLE,
      
    /* THESE ARE FOR LANGUAGE-DEPENDENT ERROR HANDLING,
     LIKE FOR TEXT PUT INTO DIALOG BOXES TO NOTIFY
     THE USER WHEN AN ERROR HAS OCCURED */
    ERROR_DATA_FILE_LOADING,
    ERROR_PROPERTIES_FILE_LOADING,
    ERROR_NO_SLIDESHOW_IMAGES,
    ERROR_UNEXPECTED
}
